resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: GH
      path: pavle9/jfrog-example

pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: Nexploit
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
            - sudo apt update
            - sudo chmod 1777 /tmp
            - sudo apt update
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - sudo apt-get install -y nodejs
            - node -v
            - npm -v
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - |
              SCAN_ID=$(nexploit-cli scan:run \
                --api https://app.neuralegion.com         \
                --bus amqps://amq.app.neuralegion.com:5672 \
                --name "💎 Broken Crystals"               \
                --crawler https://brokencrystals.com       \                                  
                --token "kg9veu3.nexa.lwc50w6zl0u6ifimiwljhf1df4hjhtwu" )      \
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID\n"
            - printf "Wait for issues ⏳\n"
            - |
              nexploit-cli scan:polling               \
                --interval 30s                        \
                --timeout 20m                         \
                --token "kg9veu3.nexa.lwc50w6zl0u6ifimiwljhf1df4hjhtwu"  \
                --breakpoint high_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token "kg9veu3.nexa.lwc50w6zl0u6ifimiwljhf1df4hjhtwu" $SCAN_ID
