resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: GH
      path: pavle9/jfrog-example

pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: Nexploit
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
            - sudo apt update
            - sudo chmod 1777 /tmp
            - sudo apt update
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            - sudo chmod +x /usr/local/bin/docker-compose
            - sudo apt install nodejs npm
            - sudo apt install --fix-broken
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - cd $res_jfrognexploitresourcePath
            - ls
            - |
              printf "NEXPLOIT_TOKEN=$int_Nexploit_NEXPLOIT_TOKEN\nREPEATER=$int_Nexploit_REPEATER\n" > .env
              cat .env
            - |
              echo $NEXPLOIT_TOKEN
              echo $REPEATER
              docker-compose --env-file=.env up -d
              docker-compose config
            - |
              SCAN_ID=$(nexploit-cli scan:run                                                \
                --name "With repeater" \
                --repeater $int_Nexploit_REPEATER                                            \
                --crawler http://brokencrystals                                       \
                --smart                                                                      \
                --token $int_Nexploit_NEXPLOIT_TOKEN)
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
            - |
              nexploit-cli scan:polling               \
                --interval 30s                        \
                --timeout 20m                         \
                --token $int_Nexploit_NEXPLOIT_TOKEN  \
                --breakpoint medium_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
