resources:
  - name: jfrognexploit
    type: GitRepo
    configuration:
      gitProvider: GH
      path: pavle9/jfrog-example
      
pipelines:
  - name: nexploit
    steps:
      - name: nexploit
        type: Bash
        configuration:
          integrations:
            - name: Nexploit
          inputResources:
            - name: jfrognexploit
        execution:
          onExecute:
            - sudo apt update
            - sudo chmod 1777 /tmp
            - sudo apt update            
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - sudo apt-get install -y nodejs
            - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
            - sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            - sudo chmod +x /usr/local/bin/docker-compose
            - |
              printf "NEXPLOIT_TOKEN=$int_Nexploit_NEXPLOIT_TOKEN\nREPEATER=$int_Nexploit_REPEATER\n" > .env
              cat .env
            - |
              docker --version
              docker-compose -f docker-compose.yml up -d
            - |
              SCAN_ID=$(nexploit-cli scan:run \
                --token $int_Nexploit_NEXPLOIT_TOKEN      \
                --id $int_Nexploit_REPEATER                 \
                --api https://app.neuralegion.com         \
                --bus amqps://amq.app.neuralegion.com:5672 \
                --name "Scan with repeater"               \
                --crawler https://brokencrystals.com)      
            - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID\n"
            - printf "Wait for issues ⏳\n"
            - |
              nexploit-cli scan:polling               \
                --interval 30s                        \
                --timeout 20m                         \
                --token $int_Nexploit_NEXPLOIT_TOKEN  \
                --breakpoint high_issue $SCAN_ID
          onComplete:
            - nexploit-cli scan:stop --token $int_Nexploit_NEXPLOIT_TOKEN $SCAN_ID
